name: MP Check Changed Files

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  mp_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        pip install --upgrade pip
        pip install -e ./packages/mp

    - name: Run mp check with changed files
      shell: bash
      run: |
        # echo "Running mp check on the following files:"
        # echo "${{ steps.get_changed_files.outputs.CHANGED_FILES }}"

        # FILE_LIST=$(echo "${{ steps.get_changed_files.outputs.CHANGED_FILES }}" | tr '\n' ' ')
        mp check --changed-files --raise-error-on-violations
